### ISSUE TITLE
UP，发现Chrome Android测试出现无法显示

### ISSUE THREAD

**Issue by Sun-ZhenXing** [KangKang0928/-Neumorphism-#1]
![Screenshot_20200813_205525](https://user-images.githubusercontent.com/44517244/90137438-331cef80-dda8-11ea-8d2b-1bb50dd9ac8b.jpg)
具体就是屏幕横着的时候，无法显示最上面的一行，还不知道是什么原因导致的🙄

**Comment by KangKang0928** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
